* The toolbus is no longer required during the build process of the aterm   library

diff --git a/aterm/configure.in b/aterm/configure.in
--- a/aterm/configure.in
+++ b/aterm/configure.in
@@ -73,84 +73,76 @@ AC_AIX
 
 AC_SET_MAKE
 
-AC_CHECK_PROG(TOOLBUS,toolbus,toolbus,true)
+AC_ARG_WITH(toolbus, 
+   [  --with-toolbus      Specify location of the ToolBus], 
+   TOOLBUS=$withval)
 
-if test ${TOOLBUS} = "true" 
-then
-  echo "The toolbus executable is not in your path, giving up!"
-  exit
+if test "a${TOOLBUS}" = "a"; then
+ dnl Try to find the location of the toolbus
+ AC_CHECK_PROG(TOOLBUS,toolbus,toolbus,false)
+ if test ${TOOLBUS} = "false" 
+ then
+   echo "Warning: toolbus not found. You might need it when developing the ATerm library." >&2
+   TOOLBUS="toolbus"
+ fi
 fi
 
 AC_ARG_WITH(java,
-[  --with-java    with Java support. Note that only jdk-1.2 (Java-2) is supported!],
-JAVA_SUBDIR=java1.2,
-)
+   [  --with-java         with Java support. Note that 
+                      only jdk-1.2 (Java-2) is supported!],
+      JAVA_SUBDIR=java1.2,)
 
 AC_ARG_WITH(gcc,
-[  --with-gcc   create gcc version of the library (libATerm-gcc.a)],
-ATERM_LIB_GCC=libATerm-gcc.a
-ASFIX_LIB_GCC=libAsFix-gcc.a
-TOOLBUS_LIB_GCC=libATB-gcc.a
-,
-)
+   [  --with-gcc          create gcc version of the library (libATerm-gcc.a)],
+      ATERM_LIB_GCC=libATerm-gcc.a
+      ASFIX_LIB_GCC=libAsFix-gcc.a
+      TOOLBUS_LIB_GCC=libATB-gcc.a,)
 
 AC_ARG_WITH(cc,
-[  --with-cc   create cc version of the library (libATerm-cc.a)],
-ATERM_LIB_CC=libATerm-cc.a
-ASFIX_LIB_CC=libAsFix-cc.a
-TOOLBUS_LIB_CC=libATB-cc.a
-,
-)
+   [  --with-cc           create cc version of the library (libATerm-cc.a)],
+      ATERM_LIB_CC=libATerm-cc.a
+      ASFIX_LIB_CC=libAsFix-cc.a
+      TOOLBUS_LIB_CC=libATB-cc.a,)
 
 AC_ARG_WITH(dbg,
-[  --with-dbg   create debug version of the library (libATerm-dbg.a)],
-ATERM_LIB_DBG=libATerm-dbg.a
-ASFIX_LIB_DBG=libAsFix-dbg.a
-TOOLBUS_LIB_DBG=libATB-dbg.a
-,
-)
+   [  --with-dbg          create debug version of the library (libATerm-dbg.a)],
+      ATERM_LIB_DBG=libATerm-dbg.a
+      ASFIX_LIB_DBG=libAsFix-dbg.a
+      TOOLBUS_LIB_DBG=libATB-dbg.a,)
 
 AC_ARG_WITH(prof,
-[  --with-prof   create debug version of the library (libATerm-prof.a)],
-ATERM_LIB_PROF=libATerm-prof.a
-ASFIX_LIB_PROF=libAsFix-prof.a
-TOOLBUS_LIB_PROF=libATB-prof.a
-,
-)
+   [  --with-prof         create debug version of the library (libATerm-prof.a)],
+      ATERM_LIB_PROF=libATerm-prof.a
+      ASFIX_LIB_PROF=libAsFix-prof.a
+      TOOLBUS_LIB_PROF=libATB-prof.a,)
 
 
 #AC_ARG_WITH(64bit,
-#[  --with-64bit   create 64 bit cc version of the library (libATerm-cc64.a)],
-#ATERM_LIB_CC64=libATerm-cc64.a
-#ASFIX_LIB_CC64=libAsFix-cc64.a
-#TOOLBUS_LIB_CC64=libATB-cc64.a
-#,
-#)
+#   [  --with-64bit         create 64 bit cc version of the library (libATerm-cc64.a)],
+#      ATERM_LIB_CC64=libATerm-cc64.a
+#      ASFIX_LIB_CC64=libAsFix-cc64.a
+#      TOOLBUS_LIB_CC64=libATB-cc64.a,)
 
 #AC_ARG_WITH(shared,
-#[  --with-shared   create a shared-library version of the library (libATerm-shared.so.${VERSION})],
-#ATERM_LIB_SHARED=libATerm-shared.so.${VERSION}
-#ASFIX_LIB_SHARED=libAsFix-shared.so.${VERSION}
-#TOOLBUS_LIB_SHARED=libATB-shared.so.${VERSION}
-#,
-#)
+#   [  --with-shared         create a shared-library version of the library (libATerm-shared.so.${VERSION})],
+#      ATERM_LIB_SHARED=libATerm-shared.so.${VERSION}
+#      ASFIX_LIB_SHARED=libAsFix-shared.so.${VERSION}
+#      TOOLBUS_LIB_SHARED=libATB-shared.so.${VERSION},)
 
 AC_ARG_WITH(all,
-[  --with-all   create all libraries (--with-{gcc,cc,dbg,prof}, NOT java)],
-ATERM_LIB_GCC=libATerm-gcc.a
-ASFIX_LIB_GCC=libAsFix-gcc.a
-TOOLBUS_LIB_GCC=libATB-gcc.a
-ATERM_LIB_CC=libATerm-cc.a
-ASFIX_LIB_CC=libAsFix-cc.a
-TOOLBUS_LIB_CC=libATB-cc.a
-ATERM_LIB_DBG=libATerm-dbg.a
-ASFIX_LIB_DBG=libAsFix-dbg.a
-TOOLBUS_LIB_DBG=libATB-dbg.a
-ATERM_LIB_PROF=libATerm-prof.a
-ASFIX_LIB_PROF=libAsFix-prof.a
-TOOLBUS_LIB_PROF=libATB-prof.a
-,
-)
+   [  --with-all          create all libraries (--with-{gcc,cc,dbg,prof}, NOT java)],
+      ATERM_LIB_GCC=libATerm-gcc.a
+      ASFIX_LIB_GCC=libAsFix-gcc.a
+      TOOLBUS_LIB_GCC=libATB-gcc.a
+      ATERM_LIB_CC=libATerm-cc.a
+      ASFIX_LIB_CC=libAsFix-cc.a
+      TOOLBUS_LIB_CC=libATB-cc.a
+      ATERM_LIB_DBG=libATerm-dbg.a
+      ASFIX_LIB_DBG=libAsFix-dbg.a
+      TOOLBUS_LIB_DBG=libATB-dbg.a
+      ATERM_LIB_PROF=libATerm-prof.a
+      ASFIX_LIB_PROF=libAsFix-prof.a
+      TOOLBUS_LIB_PROF=libATB-prof.a,)
 
 AC_SUBST(ATERM_LIB_GCC)
 AC_SUBST(ATERM_LIB_CC)
