- Version is now 1.3.4 - Fixed ToolBus configuration option so the ATerm library can now be   compiled without having the ToolBus distribution installed - Fixed bug that could cause symbols to be freed in some situations. - Incorporated JFG's improvements of ATtableRemove. - Made some code layout changes

diff --git a/aterm/configure.in b/aterm/configure.in
--- a/aterm/configure.in
+++ b/aterm/configure.in
@@ -22,7 +22,7 @@ dnl
 dnl $Id$
 
 AC_INIT(Makefile.in)
-AM_INIT_AUTOMAKE(aterm, 1.3.2)
+AM_INIT_AUTOMAKE(aterm, 1.3.4)
 
 dnl Default values
 CC_GCC=gcc
@@ -81,8 +81,8 @@ if test "a${TOOLBUS}" = "a"; then
  AC_CHECK_PROG(TOOLBUS,toolbus,toolbus,false)
  if test ${TOOLBUS} = "false" 
  then
-   echo "Warning: toolbus not found. You might need it when developing the ATerm library." >&2
-   TOOLBUS="toolbus"
+   #echo "Warning: toolbus not found. You might need it when developing the ATerm library." >&2
+   TOOLBUS="true"
  fi
 fi
 
